### ISSUE TITLE
install.packages("pacman")

### ISSUE THREAD

**Issue by jackalperstein** [fiatyus/FinalProject_FoodInsecurity#1]
I am also a lover of pacman::p_load, but my computer failed to run all of the code files due to the first line of code in every file was:

`install.packages("pacman")`

My terminal would return the error:

```
$ make cleandata
Rscript code/00_cleaningdata_TYUS.R
Installing package into 'C:/Users/jacka/AppData/Local/R/win-library/4.3'
(as 'lib' is unspecified)
Error in contrib.url(repos, "source") :
trying to use CRAN without setting a mirror
Calls: install.packages -> contrib.url
Execution halted
make: *** [makefile:4: cleandata] Error 1
```

This might be a problem with my own machine? **Regardless, I commented out this line of code in every code file and in the report.rmd and the whole project ran perfectly!**

**Comment by fiatyus** [comment]
Thanks for catching that! I actually changed it because of someone else getting an error for not having pacman downloaded but I now think that was an issue with their system. Thanks for the feedback! I've removed the install.packages on all the files so hopefully we're all set now.
