### ISSUE TITLE
issue in makefile

### ISSUE THREAD

**Issue by benkeser** [fiatyus/FinalProject_FoodInsecurity#2]
Please [remove dependency on project_image](https://github.com/fiatyus/FinalProject_FoodInsecurity/blob/1788e8f85f29f192fc65257c9efe582f739b51e1/makefile#L45) from run rule so that I don't have to rebuild your image :) 

I will regrade when you close this issue.

**Comment by fiatyus** [comment]
Hi! Just updated - i think it should work now. but I'm going back to the videos to double check

**Comment by benkeser** [comment]
looks good
