### ISSUE TITLE
issue retrieving report

### ISSUE THREAD

**Issue by benkeser** [fiatyus/FinalProject_FoodInsecurity#3]
It seems the report builds successfully in the image, but I cannot find it's location on my local computer after the container finishes running.

Could you please double check?

**Comment by fiatyus** [comment]
I haven't been able to fix this issue - are you free to meet at some point in the next few days? This is my last final so my schedule is flexible

**issues I'm noticing:**
- "CMD" doesn't seem to be working in my docker file --> I found a substitute online using "ENTRYPOINT" but I'm not sure what issues this may cause down the line (this substitution does work for running the make report statement and moving it to the final_report folder
- I've tried many iterations of the -v statement but the most that seems to happen is the "final_report" folder gets created in my local working directory (also doesn't work if I create the final report folder

**Comment by fiatyus** [comment]
Your pull request fixed the problem with pasting to the local computer thank you!
